Log:
  Level: 'info'

ExternalSecure: false
ExternalDomain: zeroschool-zitadel.onrender.com
ExternalPort: 443

TLS:
  Enabled: false

Database:
  postgres:
    Host: 'dpg-da47aj2jobas73aeuag0-a'
    Port: 5432
    Database: zitadel_db
    User:
      Username: 'zitadel_db_user'
      Password: 'XaZKXwTcIiCchiEi317FvD30faT7m4vd'
      SSL:
        Mode: 'disable'
    Admin:
      Username: 'zitadel_db_user'
      Password: 'XaZKXwTcIiCchiEi317FvD30faT7m4vd'
      SSL:
        Mode: 'disable'
