worker_processes auto;
pid /tmp/nginx.pid;

events {
    worker_connections 1024;
}

http {
    access_log /tmp/access.log;
    error_log /tmp/error.log;

    upstream zitadel {
        server 127.0.0.1:8081;
    }

    upstream loginui {
        server 127.0.0.1:3000;
    }

    server {
        listen 8080;

        client_max_body_size 10M;

        location /ui/v2/login {
            proxy_pass http://loginui;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /debug/ {
            proxy_pass http://zitadel;
        }

        location / {
            proxy_pass http://zitadel;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }
    }
}
